#!/bin/sh

# Dockの表示位置は下
defaults write com.apple.dock orientation -string "bottom"
# 最近使ったアプリをdockに表示しない
defaults write com.apple.dock show-recents -bool false
# Dockを自動的に隠すのと、速度を少し早める
defaults write com.apple.dock autohide-time-modifier -float 0.3