#!/bin/sh

# Dockの表示位置は下
defaults write com.apple.dock orientation -string "bottom"
# 最近使ったアプリをdockに表示しない
defaults write com.apple.dock show-recents -bool false
# 自動的に隠す
defaults write com.apple.dock autohide -bool true
# 隠す速度を少し早める
defaults write com.apple.dock autohide-time-modifier -float 0.3