#!/bin/sh

# スポットライトの検索から外付けメディアを除外する
# sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array "/Volumes"
# 検索オーダーとカテゴリごとの設定
defaults write com.apple.Spotlight orderedItems -array \
    '{ enabled = 1; name = APPLICATIONS; }' \
    '{ enabled = 1; name = "MENU_SPOTLIGHT_SUGGESTIONS"; }' \
    '{ enabled = 1; name = "MENU_CONVERSION"; }' \
    '{ enabled = 1; name = "MENU_EXPRESSION"; }' \
    '{ enabled = 1; name = "MENU_DEFINITION"; }' \
    '{ enabled = 1; name = "SYSTEM_PREFS"; }' \
    '{ enabled = 1; name = DOCUMENTS; }' \
    '{ enabled = 0; name = DIRECTORIES; }' \
    '{ enabled = 0; name = PRESENTATIONS; }' \
    '{ enabled = 1; name = SPREADSHEETS; }' \
    '{ enabled = 0; name = PDF; }' \
    '{ enabled = 1; name = MESSAGES; }' \
    '{ enabled = 1; name = CONTACT; }' \
    '{ enabled = 1; name = "EVENT_TODO"; }' \
    '{ enabled = 0; name = IMAGES; }' \
    '{ enabled = 1; name = BOOKMARKS; }' \
    '{ enabled = 0; name = MUSIC; }' \
    '{ enabled = 0; name = MOVIES; }' \
    '{ enabled = 0; name = FONTS; }' \
    '{ enabled = 0; name = "MENU_OTHER"; }' \
    '{ enabled = 0; name = SOURCE; }'

# インデックスを再構築する前に新しい設定を読み込む
set +e
killall mds > /dev/null 2>&1
set -e
# インデックスの再構築
sudo mdutil -E / > /dev/null