#!/bin/sh
# emacsをインストールするコマンド

set -e
cd $(dirname $0)
. ./util.sh

# プラットフォームごとの設定
case $(uname) in
	Darwin)
        sudo port install emacs-app
        ;;
    *)
        error 'サポートしていないプラットフォームです'
        ;;
esac
