#!/bin/sh
# goをインストールするスクリプト

set -e

# 引数処理
VERSION=$1
VERSION_NAME=go$VERSION
TARGET_DIR=$2
[ -z "$VERSION" ] && echo 'error: VERSIONを指定してください' 1>&2 && exit 1
[ -z "$TARGET_DIR" ] && echo 'error: インストールするディレクトリを指定してください' 1>&2 && exit 1

main()
{
    install
}

install()
{
    is_installed "$TARGET_DIR" && echo '既にインストール済みです' && exit 0
    mkdir -p "$TARGET_DIR"
    curl -sL $(package_url) | tar xz --strip=1 -C "$TARGET_DIR"
}

package_url()
{
    # 以下を参照
    # https://golang.org/dl/
    case "$(uname)" in
         Darwin) echo "https://storage.googleapis.com/golang/$VERSION_NAME.darwin-amd64.tar.gz";;
         Linux) echo "https://storage.googleapis.com/golang/$VERSION_NAME.linux-386.tar.gz";;
         *) echo 'error: パッケージURLが判別できませんでした' 1>&2 && exit 1
    esac
}

is_installed()
{
    dir="$1"
    [ -d "$dir" ] && return 0
    [ -d "$dir/bin/go" ] && return 0
    return 1
}

main
