#!/bin/sh
# MacPortsをインストールするコマンド

set -e
cd $(dirname $0)
. ./util.sh

VERSION=2.3.4

# プラットフォームごとの設定
case $(uname) in
	Darwin)
        if which port > /dev/null; then
            sudo port selfupdate
        else
            (
                TMP_DIR=$(mktemp -d)
                trap "echo ${TMP_DIR}" EXIT
                cd $TMP_DIR
                curl -O https://distfiles.macports.org/MacPorts/MacPorts-${VERSION}.tar.bz2
                tar xf MacPorts-${VERSION}.tar.bz2
                cd MacPorts-${VERSION}
                ./configure
                make
                sudo make install
            )
        fi
        ;;
    *)
        error 'サポートしていないプラットフォームです'
        ;;
esac
